language: objective-c
before_install:
- gem install cocoapods -v '0.32.1'
- npm install fir -g
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/soulight_ad_hoc.mobileprovision.enc -d -a -out scripts/profile/soulight_ad_hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xctool -workspace soulight.xcworkspace -scheme soulight -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
env:
  global:
  - APP_NAME="soulight"
  - 'DEVELOPER_NAME="iPhone Distribution: Ming Zeng (5V5696VKXV)"'
  - PROFILE_NAME="soulight_ad_hoc"
  - NONE1=KEY_PASSWORD
  - secure: hRvkjxp0X7M7zIdscxNOsrIHM75QTnRNE9T0UezqneNn8lz4Mif5anc6eIF9+iftXyvqlKhf0Zin9E2vhvj7veB/FqYJVsxXBUK7mdV8MPZqa63zwDh0PRThU2LeLOSNohCBx7u5hEyVjNGeFP8iA9XM3fvpNaDbP7hAn4EqhXQ=
  - NONE2=ENCRYPTION_SECRET
  - secure: fDA7Kdh9Ia5MEAGESZ5u+L4W5cwqYIXNjcK/r1kYrPvyn6bZYNuXYalJNx/F9pdiB1srxQuluVKkzdmUYiVfM1rzQEmJqHIvaaGY7Upy2Pni1alKnanU6QCYZXzQUQfpcAurFgP38DQjnwRw9cj5BgEaGZdFivZW/oL8mCHQMRE=
