language: objective-c
before_install:
- gem install cocoapods -v '0.32.1'
- npm install fir -g
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/soulight_ad_hoc.mobileprovision.enc
  -d -a -out scripts/profile/soulight_ad_hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
script:
- xctool -workspace soulight.xcworkspace -scheme soulight -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
env:
  global:
  - secure: RZqQZ9QTE/iy/9lV/+sfI/G7M9Y1zgyiPC9UjVVCrDfP+qX0wT8xYkEf05Oq9et3PydN1suTKF4Fb7YC70ksdhs1bh03qz9kud45Zcof5Plx63/F1sXb4Tus3g9uXwd2fgDwO0Jm8CYpGg8BkseqQBBr9KnRlEDR9ASFFx04wUw=
  - APP_NAME="soulight"
  - 'DEVELOPER_NAME="iPhone Distribution: Ming Zeng (5V5696VKXV)"'
  - PROFILE_NAME="soulight_ad_hoc."
  - secure: Cnr3V1KFmUS47ZcP1Si8W+Qpl4p0Ff8eSGtbOo3+/cAt5v2HgtuBdoj7eQRFOoJeKHUsj/mOZ42+yYcr8C+lXMGUXrDEaED/7E8E2imEIEaBuhcUeqc3GSfwzmHHXq35FUWRnl0Q1F7LetHs5JL/Xe8DDKqhde2lXyONDjAawAk=
  - secure: BKx/2RRk/Eqkt05ZNrwpHsUpm95Ye3bYFHzS15Sx5Fpsuy2TcGFZFkmyXALcIrVbFb5aLQ31Gdze9XQH2rqCv/6JgH4lntq+ZKU3m0wJ2xzOnVaZyjXbZDzJpHPqxBpq3vLuGyo3JzL/3UlXsfLr+tibdu8yCyTcr/4H/+AT19A=
  - secure: MSJxuYqrOStDjbvPiXRUQJHpv1Upv8dtm07V8mt4zAR0x06fFHAoDL9JjS28leTU91q3mng1m9bu3E4VCaToslbzKU1ZPpEL1S6p3JqmiGnI2kN5CeRczHkcxjHAcHhRlSRXh/nNRsP+Hist0UJ/6XBbXrO+P99I//42psSDmrg=
